version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=local_db
    command: "/mysql.sh"
    volumes:
      - ../.docker-data/mysql:/var/lib/mysql
      - ./mysql.sh:/mysql.sh
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin
    image: wilds/phpmyadmin:4.0.10.15
    hostname: phpmyadmin
    ports:
      - "8080:80"
    restart: on-failure
    links:
      - mysql:db

  wordpress:
    container_name: wordpress
    image: wilds/wpdevenvironment:latest
    hostname: wordpress
    environment:
      - TIMEZONE=America/New_York
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ../.docker-html:/var/www/html
      - ../.docker-certs:/usr/local/share/ca-certificates
    links:
      - mysql:db
    restart: on-failure
